services:
  nginx:
    image: nginx:cloud1
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - nginx_vol:/etc/letsencrypt
    restart: unless-stopped

  mariadb:
    image: mariadb:cloud1
    env_file:
      - .env
    volumes:
      - db_vol:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    image: wordpress:cloud1
    depends_on:
      - mariadb
      - nginx
    volumes:
      - wp_vol:/var/www/html
    env_file:
      - .env
    restart: unless-stopped

volumes:
  db_vol:
    driver: local
  wp_vol:
    driver: local
  nginx_vol:
    driver: local