services:
  nginx:
    image: nginx:cloud1
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - nginx_vol:/etc/letsencrypt
    restart: unless-stopped

  mariadb:
    image: mariadb:cloud1
    env_file:
      - .env
    volumes:
      - db_vol:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    build: wordpress:cloud1
    depends_on:
      - mariadb:cloud1
    volumes:
      - wp_vol:/var/www/html
    env_file:
      - .env


volumes:
  db_vol:
    driver: local
  wp_vol:
    driver: local
  nginx_vol:
    driver: local