services:

  wordpress:
    image: wordpress:cloud1
    depends_on:
      - mariadb
    volumes:
      - wp_vol:/var/www/html
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:cloud1
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - nginx_vol:/etc/letsencrypt
      - wp_vol:/var/www/html
    restart: always

  mariadb:
    image: mariadb:cloud1
    env_file:
      - .env
    volumes:
      - db_vol:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin:cloud1
    depends_on:
      - mariadb
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}

volumes:
  db_vol:
    driver: local
  wp_vol:
    driver: local
  nginx_vol:
    driver: local